import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.gradle.api.tasks.testing.logging.TestLogEvent
import org.gradle.kotlin.dsl.invoke

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ktor)
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.shadow)
}

group = "io.github.carlawarde"
val appVersion: String? by project
version = appVersion ?: "1.0.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.bundles.ktor.server)
    implementation(libs.bundles.logging)
    implementation(libs.bundles.observability)
    implementation(libs.bundles.koin)
    implementation(libs.bundles.exposed)
    implementation(libs.bundles.db.infra)

    testImplementation(libs.bundles.testing.common)
    testImplementation(libs.bundles.logging)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

kotlin {
    jvmToolchain(17)
}

application {
    // Define the main class for the application.
    mainClass = "io.github.carlawarde.kotlinBackendDemo.ApplicationKt"
    applicationName = "kotlin-backend-demo"
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
        }

        val integrationTest by registering(JvmTestSuite::class) {
            useJUnitJupiter()

            dependencies {
                implementation(project())
                implementation(libs.kotest.runner)
                implementation(libs.kotest.assertions.core)
                implementation(libs.kotest.property)
                implementation(libs.kotest.assertions.ktor)
                implementation(libs.kotest.extensions.testcontainers)
                implementation(libs.mockk)

                implementation(libs.testcontainers.core)
                implementation(libs.testcontainers.postgres)
                implementation(libs.testcontainers.jdbc)

                implementation(libs.hikari)

                implementation(libs.micrometer.registry.prometheus)
                implementation(libs.micrometer.core)

                implementation(libs.typesafe.config)
                implementation(libs.ktor.server.core)
                implementation(libs.ktor.server.test.host)
                implementation(libs.ktor.serialization.json)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.cio)
                implementation(libs.ktor.client.content.negotiation)

                implementation(libs.koin.ktor)
                implementation(libs.koin.test)
                implementation(libs.koin.logger)

            }
        }
    }
}

tasks.withType<Test>().configureEach {
    testLogging {
        events(
            TestLogEvent.PASSED,
            TestLogEvent.SKIPPED,
            TestLogEvent.FAILED,
            TestLogEvent.STANDARD_OUT,
            TestLogEvent.STANDARD_ERROR
        )
        showStandardStreams = true
    }
}

tasks.check {
    dependsOn(testing.suites.named("integrationTest"))
}

tasks.named<Test>("integrationTest") {
    shouldRunAfter(tasks.named("test"))
}

tasks.withType<ShadowJar> {
    archiveBaseName.set("kotlin-backend-demo")
    archiveClassifier.set("")
    archiveVersion.set(project.version.toString())
    archiveFileName.set("${archiveBaseName.get()}-${archiveVersion.get()}.jar")
}






